-- Add Markdown + HTML Formatter tool to the tools table
INSERT INTO tools (
  id,
  name,
  description,
  category,
  input_types,
  output_type,
  show_in_recommendations,
  created_at,
  updated_at
) VALUES (
  'markdown-html-formatter',
  'Markdown + HTML Formatter',
  'Convert, format, and beautify Markdown and HTML with flexible options',
  'formatter',
  ARRAY['text'],
  'text',
  true,
  NOW(),
  NOW()
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  input_types = EXCLUDED.input_types,
  output_type = EXCLUDED.output_type,
  show_in_recommendations = EXCLUDED.show_in_recommendations,
  updated_at = NOW();

-- Note: The embedding will be generated by the embedding regeneration script
-- Run: npm run regenerate-embeddings
