export const REGEX_PATTERN_TEMPLATES = {
  email: {
    id: 'email',
    category: 'Common',
    name: 'Email Addresses',
    description: 'Extract email addresses',
    pattern: '[a-zA-Z0-9._%-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}',
    flags: 'g',
    explanation: 'Matches standard email format: username@domain.extension',
    examples: [
      'john.doe@example.com',
      'user+tag@company.co.uk',
      'name_123@domain.org',
    ],
  },
  url: {
    id: 'url',
    category: 'Common',
    name: 'URLs',
    description: 'Extract URLs and web addresses',
    pattern: 'https?:\\/\\/[^\\s]+',
    flags: 'g',
    explanation: 'Matches HTTP or HTTPS URLs including paths and query strings',
    examples: [
      'https://example.com',
      'http://www.example.com/path?query=value',
      'https://sub.domain.co.uk/page#anchor',
    ],
  },
  phoneNumber: {
    id: 'phone-number',
    category: 'Common',
    name: 'Phone Numbers',
    description: 'Extract phone numbers (US format)',
    pattern: '(\\+?1[-.]?)?\\(?\\d{3}\\)?[-.]?\\d{3}[-.]?\\d{4}',
    flags: 'g',
    explanation: 'Matches US phone numbers in various formats: (123) 456-7890, 123-456-7890, +1.123.456.7890',
    examples: [
      '(555) 123-4567',
      '555.123.4567',
      '+1-555-123-4567',
      '5551234567',
    ],
  },
  number: {
    id: 'number',
    category: 'Common',
    name: 'Numbers',
    description: 'Extract all numbers (integers and decimals)',
    pattern: '-?\\d+(\\.\\d+)?',
    flags: 'g',
    explanation: 'Matches integers and decimal numbers, including negative numbers',
    examples: [
      '42',
      '-123',
      '3.14159',
      '-99.99',
    ],
  },
  integer: {
    id: 'integer',
    category: 'Common',
    name: 'Integers Only',
    description: 'Extract whole numbers',
    pattern: '-?\\d+',
    flags: 'g',
    explanation: 'Matches positive and negative whole numbers',
    examples: [
      '100',
      '-42',
      '0',
      '999999',
    ],
  },
  date: {
    id: 'date',
    category: 'Common',
    name: 'Dates (Multiple Formats)',
    description: 'Extract dates in ISO, MM/DD/YYYY, or DD/MM/YYYY formats',
    pattern: '(\\d{4}[\\-/](?:0?[1-9]|1[0-2])[\\-/](?:0?[1-9]|[12]\\d|3[01])|(?:0?[1-9]|1[0-2])[\\-/](?:0?[1-9]|[12]\\d|3[01])[\\-/](?:\\d{4}|\\d{2})|(?:0?[1-9]|[12]\\d|3[01])[\\-/](?:0?[1-9]|1[0-2])[\\-/](?:\\d{4}|\\d{2}))',
    flags: 'g',
    explanation: 'Matches ISO format (2024-02-14), US (12/25/2023), or European (14-02-2024) dates',
    examples: [
      '2024-02-14',
      '12/25/2023',
      '1/1/23',
      '14-02-2024',
      '2024/02/14',
    ],
  },
  isodate: {
    id: 'isodate',
    category: 'Common',
    name: 'ISO Dates (YYYY-MM-DD)',
    description: 'Extract ISO 8601 formatted dates',
    pattern: '\\d{4}[\\-/](?:0[1-9]|1[0-2])[\\-/](?:0[1-9]|[12]\\d|3[01])',
    flags: 'g',
    explanation: 'Matches ISO date format: 2024-02-14, 2024/02/14, etc.',
    examples: [
      '2024-02-14',
      '2024/02/14',
      '2023-12-25',
      '2024-01-01',
    ],
  },
  datetime: {
    id: 'datetime',
    category: 'Common',
    name: 'ISO DateTime (YYYY-MM-DD HH:MM:SS)',
    description: 'Extract ISO datetime stamps',
    pattern: '\\d{4}[\\-/](?:0[1-9]|1[0-2])[\\-/](?:0[1-9]|[12]\\d|3[01])\\s+(?:[01]?\\d|2[0-3]):(?:[0-5]?\\d)(?::(?:[0-5]?\\d))?',
    flags: 'g',
    explanation: 'Matches ISO datetime: 2024-02-14 13:55:23',
    examples: [
      '2024-02-14 13:55:23',
      '2024-02-14 09:15',
      '2023-12-25 23:59:59',
    ],
  },
  time: {
    id: 'time',
    category: 'Common',
    name: 'Time (HH:MM:SS)',
    description: 'Extract time in HH:MM or HH:MM:SS format',
    pattern: '([01]?\\d|2[0-3]):([0-5]?\\d)(:([0-5]?\\d))?',
    flags: 'g',
    explanation: 'Matches time in 24-hour format: 14:30:45 or 9:05',
    examples: [
      '14:30:45',
      '09:15',
      '23:59:59',
      '0:00',
    ],
  },
  uuid: {
    id: 'uuid',
    category: 'Identifiers',
    name: 'UUIDs',
    description: 'Extract UUID/GUID strings',
    pattern: '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}',
    flags: 'gi',
    explanation: 'Matches UUID format: 550e8400-e29b-41d4-a716-446655440000',
    examples: [
      '550e8400-e29b-41d4-a716-446655440000',
      'f47ac10b-58cc-4372-a567-0e02b2c3d479',
      '6ba7b810-9dad-11d1-80b4-00c04fd430c8',
    ],
  },
  ipv4: {
    id: 'ipv4',
    category: 'Network',
    name: 'IPv4 Addresses',
    description: 'Extract IPv4 addresses',
    pattern: '(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)',
    flags: 'g',
    explanation: 'Matches valid IPv4 addresses: 192.168.1.1',
    examples: [
      '192.168.1.1',
      '10.0.0.1',
      '255.255.255.255',
      '0.0.0.0',
    ],
  },
  hexColor: {
    id: 'hex-color',
    category: 'Colors',
    name: 'Hex Colors',
    description: 'Extract hex color codes',
    pattern: '#(?:[0-9a-f]{3}){1,2}\\b',
    flags: 'gi',
    explanation: 'Matches hex color codes: #FF5733 or #F57',
    examples: [
      '#FF5733',
      '#FFF',
      '#000000',
      '#abc',
    ],
  },
  orderId: {
    id: 'order-id',
    category: 'Business',
    name: 'Order Numbers',
    description: 'Extract order numbers (Order #1234)',
    pattern: 'Order #?(\\d+)',
    flags: 'gi',
    explanation: 'Matches order identifiers: Order #10293 or Order 10293',
    examples: [
      'Order #10293',
      'order 994',
      'ORDER #7783',
    ],
  },
  skuCode: {
    id: 'sku-code',
    category: 'Business',
    name: 'SKU Codes',
    description: 'Extract product SKU codes',
    pattern: '[A-Z]{2,}-\\d{4,}(?:-[A-Z0-9]+)?',
    flags: 'g',
    explanation: 'Matches product SKUs like: ABC-1234 or ABC-1234-XYZ',
    examples: [
      'SKU-2024',
      'ABC-1234-XYZ',
      'PROD-9999',
    ],
  },
  word: {
    id: 'word',
    category: 'Text',
    name: 'Words',
    description: 'Extract all words (alphanumeric sequences)',
    pattern: '\\b\\w+\\b',
    flags: 'g',
    explanation: 'Matches complete words, including alphanumeric and underscores',
    examples: [
      'hello',
      'WORLD123',
      'test_word',
      'unicode',
    ],
  },
  quotedText: {
    id: 'quoted-text',
    category: 'Text',
    name: 'Quoted Text',
    description: 'Extract text within quotes',
    pattern: '["\']([^"\']*)["\']',
    flags: 'g',
    explanation: 'Matches text inside single or double quotes',
    examples: [
      '"Hello, World!"',
      "'Single quotes'",
      '"Mixed \'quotes\'"',
    ],
  },
  htmlTag: {
    id: 'html-tag',
    category: 'Web',
    name: 'HTML Tags',
    description: 'Extract HTML tag names',
    pattern: '<(/?)([a-z][a-z0-9]*)\\b[^>]*>',
    flags: 'gi',
    explanation: 'Matches HTML opening and closing tags: <div>, </span>, etc',
    examples: [
      '<div>',
      '</span>',
      '<img src="test.jpg">',
      '<a href="#">link</a>',
    ],
  },
  jsonKey: {
    id: 'json-key',
    category: 'Web',
    name: 'JSON Keys',
    description: 'Extract JSON object keys',
    pattern: '"([^"]+)"\\s*:',
    flags: 'g',
    explanation: 'Matches JSON property names (captures the key name)',
    examples: [
      '"name": "John"',
      '"email": "john@example.com"',
      '"active": true',
    ],
  },
  hashtag: {
    id: 'hashtag',
    category: 'Social',
    name: 'Hashtags',
    description: 'Extract hashtags from social media',
    pattern: '#\\w+',
    flags: 'g',
    explanation: 'Matches hashtags: #hashtag #programming',
    examples: [
      '#hashtag',
      '#programming',
      '#WebDevelopment123',
    ],
  },
  mention: {
    id: 'mention',
    category: 'Social',
    name: 'Mentions',
    description: 'Extract @mentions from social media',
    pattern: '@\\w+',
    flags: 'g',
    explanation: 'Matches mentions: @username @john_doe',
    examples: [
      '@username',
      '@john_doe',
      '@Developer123',
    ],
  },
  creditCard: {
    id: 'credit-card',
    category: 'Payment',
    name: 'Credit Card Numbers (Pattern)',
    description: 'Extract credit card number patterns',
    pattern: '\\b\\d{4}[\\s-]?\\d{4}[\\s-]?\\d{4}[\\s-]?\\d{4}\\b',
    flags: 'g',
    explanation: 'Matches 16-digit credit card format with optional separators',
    examples: [
      '1234 5678 9012 3456',
      '1234-5678-9012-3456',
      '1234567890123456',
    ],
  },
  zipCode: {
    id: 'zip-code',
    category: 'Location',
    name: 'US Zip Codes',
    description: 'Extract US zip codes',
    pattern: '\\b\\d{5}(-\\d{4})?\\b',
    flags: 'g',
    explanation: 'Matches US zip codes: 12345 or 12345-6789',
    examples: [
      '10001',
      '90210-1234',
      '02134',
    ],
  },
  ssn: {
    id: 'ssn',
    category: 'Location',
    name: 'Social Security Numbers',
    description: 'Extract SSN pattern (US)',
    pattern: '\\b\\d{3}-\\d{2}-\\d{4}\\b',
    flags: 'g',
    explanation: 'Matches Social Security number format: 123-45-6789',
    examples: [
      '123-45-6789',
      '000-00-0000',
    ],
  },
  filename: {
    id: 'filename',
    category: 'Web',
    name: 'Filenames with Extensions',
    description: 'Extract filenames with their extensions',
    pattern: '[\\w-]+\\.(?:png|jpg|jpeg|gif|pdf|doc|docx|xls|xlsx|zip)',
    flags: 'gi',
    explanation: 'Matches filenames with common file extensions',
    examples: [
      'document.pdf',
      'image-2024.jpg',
      'report.xlsx',
    ],
  },
  iprange: {
    id: 'iprange',
    category: 'Network',
    name: 'CIDR IP Ranges',
    description: 'Extract CIDR notation IP ranges',
    pattern: '(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)/\\d{1,2}',
    flags: 'g',
    explanation: 'Matches CIDR notation like 192.168.1.0/24',
    examples: [
      '192.168.0.0/16',
      '10.0.0.0/8',
      '172.16.0.0/12',
    ],
  },
  camelcase: {
    id: 'camelcase',
    category: 'Text',
    name: 'camelCase Words',
    description: 'Extract camelCase variable names',
    pattern: '[a-z]+(?:[A-Z][a-z]+)*',
    flags: 'g',
    explanation: 'Matches camelCase formatted words like myVariable',
    examples: [
      'myVariable',
      'getUserData',
      'isActive',
    ],
  },
  snakecase: {
    id: 'snakecase',
    category: 'Text',
    name: 'snake_case Words',
    description: 'Extract snake_case variable names',
    pattern: '[a-z_]+[a-z0-9_]*',
    flags: 'g',
    explanation: 'Matches snake_case formatted words like my_variable',
    examples: [
      'my_variable',
      'user_id',
      'is_active_flag',
    ],
  },
  mdheader: {
    id: 'mdheader',
    category: 'Web',
    name: 'Markdown Headers',
    description: 'Extract Markdown heading levels',
    pattern: '^#{1,6}\\s+(.+)$',
    flags: 'gm',
    explanation: 'Matches Markdown headers: # H1, ## H2, etc.',
    examples: [
      '# Main Title',
      '## Section Header',
      '### Subsection',
    ],
  },
  mdlink: {
    id: 'mdlink',
    category: 'Web',
    name: 'Markdown Links',
    description: 'Extract Markdown link URLs',
    pattern: '\\[([^\\]]+)\\]\\(([^)]+)\\)',
    flags: 'g',
    explanation: 'Captures Markdown links: [text](url)',
    examples: [
      '[Google](https://google.com)',
      '[GitHub](https://github.com)',
    ],
  },
  version: {
    id: 'version',
    category: 'Common',
    name: 'Semantic Versions',
    description: 'Extract semantic version numbers',
    pattern: '\\b(\\d+)\\.(\\d+)\\.(\\d+)(?:-(\\w+))?\\b',
    flags: 'g',
    explanation: 'Matches semantic versioning: 1.2.3 or 1.0.0-beta',
    examples: [
      '1.0.0',
      '2.1.3',
      '3.0.0-alpha',
    ],
  },
  currency: {
    id: 'currency',
    category: 'Payment',
    name: 'Currency Amounts',
    description: 'Extract currency values with symbols',
    pattern: '[$£€¥]\\s?\\d+(?:,?\\d{3})*(?:\\.\\d{2})?',
    flags: 'g',
    explanation: 'Matches prices: $99.99, £50, €100,50',
    examples: [
      '$19.99',
      '£1,000.50',
      '€5.99',
    ],
  },
  username: {
    id: 'username',
    category: 'Common',
    name: 'Usernames',
    description: 'Extract usernames from text',
    pattern: '@\\w{3,16}\\b',
    flags: 'g',
    explanation: 'Matches usernames: @username, @john_doe',
    examples: [
      '@username',
      '@john_doe123',
      '@developer',
    ],
  },
};

export function getPatternTemplatesByCategory() {
  const categories = {};
  
  Object.values(REGEX_PATTERN_TEMPLATES).forEach(template => {
    if (!categories[template.category]) {
      categories[template.category] = [];
    }
    categories[template.category].push(template);
  });
  
  return categories;
}

export function getPatternTemplate(id) {
  return REGEX_PATTERN_TEMPLATES[id] || null;
}

export function getAllPatternTemplates() {
  return Object.values(REGEX_PATTERN_TEMPLATES);
}
